// flow-typed signature: 983b71cbd21410f5909dcbd02ae3d70e
// flow-typed version: <<STUB>>/@braiins/eslint-config_v^0.2.3/flow_v0.93.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   '@braiins/eslint-config'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module '@braiins/eslint-config' {
    declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module '@braiins/eslint-config/rules/best-practices' {
    declare module.exports: any;
}

declare module '@braiins/eslint-config/rules/errors' {
    declare module.exports: any;
}

declare module '@braiins/eslint-config/rules/es6' {
    declare module.exports: any;
}

declare module '@braiins/eslint-config/rules/flow' {
    declare module.exports: any;
}

declare module '@braiins/eslint-config/rules/imports' {
    declare module.exports: any;
}

declare module '@braiins/eslint-config/rules/jest' {
    declare module.exports: any;
}

declare module '@braiins/eslint-config/rules/node' {
    declare module.exports: any;
}

declare module '@braiins/eslint-config/rules/react-a11y' {
    declare module.exports: any;
}

declare module '@braiins/eslint-config/rules/react' {
    declare module.exports: any;
}

declare module '@braiins/eslint-config/rules/strict' {
    declare module.exports: any;
}

declare module '@braiins/eslint-config/rules/style' {
    declare module.exports: any;
}

declare module '@braiins/eslint-config/rules/variables' {
    declare module.exports: any;
}

// Filename aliases
declare module '@braiins/eslint-config/index' {
    declare module.exports: $Exports<'@braiins/eslint-config'>;
}
declare module '@braiins/eslint-config/index.js' {
    declare module.exports: $Exports<'@braiins/eslint-config'>;
}
declare module '@braiins/eslint-config/rules/best-practices.js' {
    declare module.exports: $Exports<'@braiins/eslint-config/rules/best-practices'>;
}
declare module '@braiins/eslint-config/rules/errors.js' {
    declare module.exports: $Exports<'@braiins/eslint-config/rules/errors'>;
}
declare module '@braiins/eslint-config/rules/es6.js' {
    declare module.exports: $Exports<'@braiins/eslint-config/rules/es6'>;
}
declare module '@braiins/eslint-config/rules/flow.js' {
    declare module.exports: $Exports<'@braiins/eslint-config/rules/flow'>;
}
declare module '@braiins/eslint-config/rules/imports.js' {
    declare module.exports: $Exports<'@braiins/eslint-config/rules/imports'>;
}
declare module '@braiins/eslint-config/rules/jest.js' {
    declare module.exports: $Exports<'@braiins/eslint-config/rules/jest'>;
}
declare module '@braiins/eslint-config/rules/node.js' {
    declare module.exports: $Exports<'@braiins/eslint-config/rules/node'>;
}
declare module '@braiins/eslint-config/rules/react-a11y.js' {
    declare module.exports: $Exports<'@braiins/eslint-config/rules/react-a11y'>;
}
declare module '@braiins/eslint-config/rules/react.js' {
    declare module.exports: $Exports<'@braiins/eslint-config/rules/react'>;
}
declare module '@braiins/eslint-config/rules/strict.js' {
    declare module.exports: $Exports<'@braiins/eslint-config/rules/strict'>;
}
declare module '@braiins/eslint-config/rules/style.js' {
    declare module.exports: $Exports<'@braiins/eslint-config/rules/style'>;
}
declare module '@braiins/eslint-config/rules/variables.js' {
    declare module.exports: $Exports<'@braiins/eslint-config/rules/variables'>;
}
