// flow-typed signature: 9d77ba640e8c3454b4b8fb9433ac6ba9
// flow-typed version: <<STUB>>/eslint-restricted-globals_v^0.2.0/flow_v0.93.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'eslint-restricted-globals'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'eslint-restricted-globals' {
    declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */

// Filename aliases
declare module 'eslint-restricted-globals/index' {
    declare module.exports: $Exports<'eslint-restricted-globals'>;
}
declare module 'eslint-restricted-globals/index.js' {
    declare module.exports: $Exports<'eslint-restricted-globals'>;
}
